apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  selector:
    matchLabels:
      app: apache
      tier: web
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: apache
        tier: web
        track: stable
    spec:
      containers:
        - name: hello
          image: serush46/apache:${BUILD_NUMBER}
          ports:
            - name: http
              containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-lb
spec:
  selector:
    app: apache
    tier: web
  ports:
  - protocol: TCP
    port: 3146
    targetPort: http
  type: LoadBalancer
